In [36]:
import collections
import numpy as np

from random import choice
from math import hypot

In [2]:
Card = collections.namedtuple('Card', ['rank', 'suit'])

In [3]:
class FrenchDeck:
    ranks = [str(n) for n in range(2, 11)] + list('JQKA')
    suits = ['spades', 'diamonds', 'clubs', 'hearts']
    
    def __init__(self):
        self._cards = [Card(rank, suit) for suit in self.suits
                                        for rank in self.ranks]
        
    def __len__(self):
        return len(self._cards)
    
    def __getitem__(self, position):
        return self._cards[position]

In [4]:
beer_card = Card('7', 'diamonds')

In [5]:
beer_card

Card(rank='7', suit='diamonds')

In [6]:
deck = FrenchDeck()

In [7]:
len(deck)

52

In [8]:
deck[1]

Card(rank='3', suit='spades')

In [9]:
choice(deck)

Card(rank='10', suit='spades')

In [10]:
deck[:3]

[Card(rank='2', suit='spades'),
 Card(rank='3', suit='spades'),
 Card(rank='4', suit='spades')]

In [11]:
for card in deck:
    print(card)
    break

Card(rank='2', suit='spades')


In [12]:
beer_card in deck

True

In [13]:
suit_values = dict(spades=3, hearts=2, diamonds=1, clubs=0)

def spades_high(card):
    rank_value = FrenchDeck.ranks.index(card.rank)
    return rank_value * len(suit_values) + suit_values[card.suit]

In [14]:
for card in sorted(deck, key=spades_high):
    print(card)

Card(rank='2', suit='clubs')
Card(rank='2', suit='diamonds')
Card(rank='2', suit='hearts')
Card(rank='2', suit='spades')
Card(rank='3', suit='clubs')
Card(rank='3', suit='diamonds')
Card(rank='3', suit='hearts')
Card(rank='3', suit='spades')
Card(rank='4', suit='clubs')
Card(rank='4', suit='diamonds')
Card(rank='4', suit='hearts')
Card(rank='4', suit='spades')
Card(rank='5', suit='clubs')
Card(rank='5', suit='diamonds')
Card(rank='5', suit='hearts')
Card(rank='5', suit='spades')
Card(rank='6', suit='clubs')
Card(rank='6', suit='diamonds')
Card(rank='6', suit='hearts')
Card(rank='6', suit='spades')
Card(rank='7', suit='clubs')
Card(rank='7', suit='diamonds')
Card(rank='7', suit='hearts')
Card(rank='7', suit='spades')
Card(rank='8', suit='clubs')
Card(rank='8', suit='diamonds')
Card(rank='8', suit='hearts')
Card(rank='8', suit='spades')
Card(rank='9', suit='clubs')
Card(rank='9', suit='diamonds')
Card(rank='9', suit='hearts')
Card(rank='9', suit='spades')
Card(rank='10', suit='clubs')
Ca

In [15]:
FrenchDeck.ranks.index('2')

0

In [16]:
class Vector:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
        
    def __repr__(self):
        return 'Vector(%r, %r)' % (self.x, self.y)
    
    def __abs__(self):
        return hypot(self.x, self.y)
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Vector(x, y)
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar, self.y * scalar)

In [17]:
[(x, y) for x in 'abcd' for y in '1234']

[('a', '1'),
 ('a', '2'),
 ('a', '3'),
 ('a', '4'),
 ('b', '1'),
 ('b', '2'),
 ('b', '3'),
 ('b', '4'),
 ('c', '1'),
 ('c', '2'),
 ('c', '3'),
 ('c', '4'),
 ('d', '1'),
 ('d', '2'),
 ('d', '3'),
 ('d', '4')]

In [29]:
s1 = (1,2,3)
s2 = 3,4,5

In [26]:
s1 += s2

In [34]:
s1 += (123,)

In [28]:
import dis

In [35]:
s1

(1, 2, 3, 123)

In [57]:
a = np.arange(24).reshape((2,3,4))

In [58]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [60]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
a[1, 2]

array([20, 21, 22, 23])

In [66]:
a[..., 2]

array([[ 2,  6, 10],
       [14, 18, 22]])

In [67]:
l = [1,2,3]

In [68]:
id(l)

139699729893000

In [69]:
l *= 2

In [70]:
id(l)

139699729893000

In [71]:
t = (1,2,3)

In [72]:
id(t)

139699726275640

In [73]:
t *= 2

In [74]:
id(t)

139699729853032

In [75]:
t = (1,2, [30, 40])

In [76]:
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [77]:
t

(1, 2, [30, 40, 50, 60])

In [78]:
dis.dis("t[2] += [50, 60]")

  1           0 LOAD_NAME                0 (t)
              3 LOAD_CONST               0 (2)
              6 DUP_TOP_TWO
              7 BINARY_SUBSCR
              8 LOAD_CONST               1 (50)
             11 LOAD_CONST               2 (60)
             14 BUILD_LIST               2
             17 INPLACE_ADD
             18 ROT_THREE
             19 STORE_SUBSCR
             20 LOAD_CONST               3 (None)
             23 RETURN_VALUE


In [79]:
import bisect, sys

In [93]:
HAYSTACK = [1,4,5,6,8,12,15,20,21,23,23,26,29,30]
NEEDLES = [0,1,2,5,8,10,22,23,29, 30,31]

ROW_FMT = '{0:5d} @ {1:2d} {2}{0:<2d}'

In [94]:
def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))

In [99]:
bisect_fn = bisect.bisect_left

In [100]:
print('DEMO: ', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect_fn)

DEMO:  bisect_left
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
   31 @ 14   |  |  |  |  |  |  |  |  |  |  |  |  |  |31
   30 @ 13   |  |  |  |  |  |  |  |  |  |  |  |  |30
   29 @ 12   |  |  |  |  |  |  |  |  |  |  |  |29
   23 @  9   |  |  |  |  |  |  |  |  |23
   22 @  9   |  |  |  |  |  |  |  |  |22
   10 @  5   |  |  |  |  |10
    8 @  4   |  |  |  |8 
    5 @  2   |  |5 
    2 @  1   |2 
    1 @  0 1 
    0 @  0 0 


In [98]:
print('DEMO: ', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect_fn)

DEMO:  bisect
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
   31 @ 14   |  |  |  |  |  |  |  |  |  |  |  |  |  |31
   30 @ 14   |  |  |  |  |  |  |  |  |  |  |  |  |  |30
   29 @ 13   |  |  |  |  |  |  |  |  |  |  |  |  |29
   23 @ 11   |  |  |  |  |  |  |  |  |  |  |23
   22 @  9   |  |  |  |  |  |  |  |  |22
   10 @  5   |  |  |  |  |10
    8 @  5   |  |  |  |  |8 
    5 @  3   |  |  |5 
    2 @  1   |2 
    1 @  1   |1 
    0 @  0 0 


In [101]:
import random

In [102]:
SIZE = 7

In [103]:
random.seed(1729)

In [104]:
my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [106]:
from array import array
from random import random

In [117]:
floats = array('d', (random() for i in range(10**5)))

In [118]:
floats[-1]

0.023445696082383893

In [119]:
fp = open('floats.bin', 'wb')

floats.tofile(fp)
fp.close()

In [120]:
floats2 = array('d')

In [121]:
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**5)
fp.close()

In [122]:
floats2[-1]

0.023445696082383893

In [123]:
floats == floats2

True

In [125]:
floats.typecode

'd'

In [129]:
numbers = array('h', range(-2, 3))

In [130]:
numbers

array('h', [-2, -1, 0, 1, 2])

In [131]:
memv = memoryview(numbers)

In [132]:
len(memv)

5

In [133]:
memv[0]

-2

In [134]:
memv_oct = memv.cast('B')

In [137]:
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [139]:
memv_oct[5] = 4

In [140]:
numbers

array('h', [-2, -1, 1024, 1, 2])

In [141]:
from time import perf_counter as pc

In [145]:
N = 10**7

In [146]:
t0 = pc()
l = []
for i in range(N):
    l.append(i)
print(pc()-t0)

1.9453051069867797


In [147]:
t0 = pc()
l = [i for i in range(N)]
print(pc()-t0)

0.7124207019951427


In [149]:
from collections import deque

In [150]:
dq = deque(range(10), maxlen=10)

In [151]:
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
dq.rotate(3)

In [153]:
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [154]:
dq.append(11)

In [155]:
dq

deque([8, 9, 0, 1, 2, 3, 4, 5, 6, 11])

In [157]:
__builtin__.__dict__

{'ArithmeticError': ArithmeticError,
 'AssertionError': AssertionError,
 'AttributeError': AttributeError,
 'BaseException': BaseException,
 'BlockingIOError': BlockingIOError,
 'BrokenPipeError': BrokenPipeError,
 'BufferError': BufferError,
 'BytesWarning': BytesWarning,
 'ChildProcessError': ChildProcessError,
 'ConnectionAbortedError': ConnectionAbortedError,
 'ConnectionError': ConnectionError,
 'ConnectionRefusedError': ConnectionRefusedError,
 'ConnectionResetError': ConnectionResetError,
 'DeprecationWarning': DeprecationWarning,
 'EOFError': EOFError,
 'Ellipsis': Ellipsis,
 'EnvironmentError': OSError,
 'Exception': Exception,
 'False': False,
 'FileExistsError': FileExistsError,
 'FileNotFoundError': FileNotFoundError,
 'FloatingPointError': FloatingPointError,
 'FutureWarning': FutureWarning,
 'GeneratorExit': GeneratorExit,
 'IOError': OSError,
 'ImportError': ImportError,
 'ImportWarning': ImportWarning,
 'IndentationError': IndentationError,
 'IndexError': IndexError,
 '

In [160]:
tt = (1, 2, (30, 40))

In [164]:
hash('a')

2813147095168596766

In [165]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [176]:
TEXT = '''The Zen of Python, by Tim Peters
Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!'''

In [180]:
print(TEXT)

The Zen of Python, by Tim Peters
Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [213]:
import re
import collections

In [217]:
WORD_RE = re.compile(r'\w+')

index = collections.defaultdict(list)
for line_no, line in enumerate(TEXT.split('\n'), 1):
    for match in re.finditer(r'\w+', line):
        word = match.group()
        column_no = match.start() + 1
        location = (line_no, column_no)
        
        index[word].append(location)
        
for word in sorted(index, key=str.upper):
    print(word, index[word])

a [(18, 48), (19, 53)]
Although [(10, 1), (15, 1), (17, 1)]
ambiguity [(13, 16)]
and [(14, 23)]
are [(20, 12)]
aren [(9, 15)]
at [(15, 38)]
bad [(18, 50)]
be [(14, 14), (15, 27), (19, 50)]
beats [(10, 23)]
Beautiful [(2, 1)]
better [(2, 14), (3, 13), (4, 11), (5, 12), (6, 9), (7, 11), (16, 8), (17, 25)]
break [(9, 40)]
by [(1, 20)]
cases [(9, 9)]
complex [(4, 23)]
Complex [(5, 1)]
complicated [(5, 24)]
counts [(8, 13)]
dense [(7, 23)]
do [(14, 64), (20, 48)]
Dutch [(15, 61)]
easy [(19, 26)]
enough [(9, 30)]
Errors [(11, 1)]
explain [(18, 34), (19, 34)]
Explicit [(3, 1)]
explicitly [(12, 8)]
face [(13, 8)]
first [(15, 41)]
Flat [(6, 1)]
good [(19, 55)]
great [(20, 28)]
guess [(13, 52)]
hard [(18, 26)]
honking [(20, 20)]
idea [(18, 54), (19, 60), (20, 34)]
If [(18, 1), (19, 1)]
implementation [(18, 8), (19, 8)]
implicit [(3, 25)]
In [(13, 1)]
is [(2, 11), (3, 10), (4, 8), (5, 9), (6, 6), (7, 8), (16, 5), (17, 16), (18, 23), (19, 23)]
it [(14, 67), (18, 43), (19, 43)]
let [(20, 42)]
may [

In [204]:
d = {'one': 1, 'two': 2, 'three': 3}

In [205]:
d.update({'four': 4})

In [206]:
d

{'four': 4, 'one': 1, 'three': 3, 'two': 2}

In [207]:
d.keys()

dict_keys(['two', 'four', 'one', 'three'])

In [208]:
d.values()

dict_values([2, 4, 1, 3])

In [210]:
d.items()

dict_items([('two', 2), ('four', 4), ('one', 1), ('three', 3)])

In [211]:
d.update({'two': 22})

In [212]:
d

{'four': 4, 'one': 1, 'three': 3, 'two': 22}

In [260]:
class StrKeyDict(dict):
    
    def __missing__(self, key):
        print('*'*80)
        print('Missing method')
        if isinstance(key, str):
            print('    keyerror')
            raise KeyError
        print('    return self[', str(key), ']')
        print('*'*80)
        return self[str(key)]
    
    def get(self, key, default=None):
        print('Get method')
        try:
            return self[key]
        except KeyError:
            return default
        
    def __contains__(self, key):
        print('Contains method')
        return key in self.keys() or str(key) in self.keys()

In [276]:
d = StrKeyDict([('2', 'two'), ('4', 'four'), (1, 'one')])

In [277]:
d

{'4': 'four', '2': 'two', '1': 'one'}

In [278]:
d['2']

'two'

In [279]:
d[4]

********************************************************************************
Missing method
    return self[ 4 ]
********************************************************************************


'four'

In [280]:
d['3']

********************************************************************************
Missing method
    keyerror


KeyError: 

In [281]:
d[3]

********************************************************************************
Missing method
    return self[ 3 ]
********************************************************************************
********************************************************************************
Missing method
    keyerror


KeyError: 

In [282]:
d.get(2)

********************************************************************************
Missing method
    return self[ 2 ]
********************************************************************************


'two'

In [283]:
d.get('2')

'two'

In [284]:
d.get('3')

********************************************************************************
Missing method
    keyerror


In [285]:
d.get(3)

********************************************************************************
Missing method
    return self[ 3 ]
********************************************************************************
********************************************************************************
Missing method
    keyerror


In [286]:
d[3]

********************************************************************************
Missing method
    return self[ 3 ]
********************************************************************************
********************************************************************************
Missing method
    keyerror


KeyError: 

In [287]:
2 in d

Contains method


True

In [288]:
3 in d

Contains method


False

In [289]:
import collections

class StrKeyDict(collections.UserDict):
    
    def __missing__(self, key):
        print('*'*80)
        print('Missing method')
        if isinstance(key, str):
            print('    keyerror')
            raise KeyError
        print('    return self[', str(key), ']')
        print('*'*80)
        return self[str(key)]
    
    def __setitem__(self, key, item):
        self.data[str(key)] = item
        
    def __contains__(self, key):
        print('Contains method')
        return str(key) in self.data

In [290]:
d.data

{'1': 'one', '2': 'two', '4': 'four'}

In [291]:
d

{'4': 'four', '2': 'two', '1': 'one'}

In [293]:
d.__dict__

{'data': {'1': 'one', '2': 'two', '4': 'four'}}

In [294]:
from types import MappingProxyType

In [295]:
d = {1: 'A'}

In [296]:
d_proxy = MappingProxyType(d)

In [298]:
d_proxy

mappingproxy({1: 'A'})

In [299]:
d_proxy[1]

'A'

In [300]:
d_proxy[2] = 'X'

TypeError: 'mappingproxy' object does not support item assignment

In [301]:
d[2] = 'X'

In [302]:
d

{1: 'A', 2: 'X'}

In [303]:
d_proxy

mappingproxy({1: 'A', 2: 'X'})

In [304]:
dis.dis('{1}')

  1           0 LOAD_CONST               0 (1)
              3 BUILD_SET                1
              6 RETURN_VALUE


In [305]:
dis.dis('set([1])')

  1           0 LOAD_NAME                0 (set)
              3 LOAD_CONST               0 (1)
              6 BUILD_LIST               1
              9 CALL_FUNCTION            1 (1 positional, 0 keyword pair)
             12 RETURN_VALUE


In [306]:
dis.dis('set(1)')

  1           0 LOAD_NAME                0 (set)
              3 LOAD_CONST               0 (1)
              6 CALL_FUNCTION            1 (1 positional, 0 keyword pair)
              9 RETURN_VALUE


In [308]:
d = {(1,2): 'mnogo'}

In [309]:
d

{(1, 2): 'mnogo'}

In [314]:
d.update({(1,3): 'malo'})

In [315]:
d

{(1, 2): 'mnogo', (1, 3): 'malo'}

In [316]:
1 == 1.0

True

In [323]:
4.000001 == 1.0+1.0+1.0+1.000001

True

In [324]:
hash(1)

1

In [339]:
hash(1.00000000000001)

23041

In [342]:
bin(1.0)

TypeError: 'float' object cannot be interpreted as an integer